# Generated by Django 6.0.5 on 2026-05-26 15:03

from django.db import migrations, models


def rename_technician_role(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='technician').update(role='technicien')


def restore_technician_role(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='technicien').update(role='technician')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_technician_role, restore_technician_role),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('technicien', 'Technicien'), ('admin', 'Administrateur')], default='user', max_length=20, verbose_name='Rôle'),
        ),
    ]
