# Generated by Django 6.0.5 on 2026-05-25 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules, utilisés par le module IA', verbose_name='Mots-clés IA')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('pending_assignment', "En attente d'affectation"), ('assigned', 'Affecté'), ('in_progress', 'En cours de traitement'), ('waiting_info', "En attente d'information"), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('cancelled', 'Annulé')], default='open', max_length=30, verbose_name='Statut')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/', verbose_name='Pièce jointe')),
                ('ai_suggested_priority', models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=20, verbose_name="Priorité suggérée par l'IA")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('ai_suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggested_tickets', to='tickets.category', verbose_name="Catégorie suggérée par l'IA")),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Technicien affecté')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50, verbose_name='Champ modifié')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='Ancienne valeur')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='Nouvelle valeur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-timestamp'],
            },
        ),
    ]
