# Generated by Django 6.0.5 on 2026-05-28 19:57

import apps.tickets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/attachments/', validators=[apps.tickets.validators.validate_file_extension, apps.tickets.validators.validate_file_size], verbose_name='Pièce jointe'),
        ),
    ]
